# Usar una imagen base de Node.js para desarrollo
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar TODAS las dependencias (incluidas las de desarrollo como nodemon)
RUN npm install

# Copiamos el resto del código. El volumen lo sobreescribirá en tiempo de ejecución,
# pero esto asegura que la imagen se pueda construir por sí misma.
COPY . .

# El puerto 3000 ya está expuesto en el docker-compose.yml principal.
# El comando para iniciar el servidor en modo desarrollo con nodemon.
CMD [ "npm", "run", "dev" ]
